services:
  app:
    build:
      context: .
    restart: always
    volumes:
      - static-data:/app/staticfiles/
      - media-data:/app/media

  proxy:
    build:
      context: ./proxy
    restart: always
    volumes:
      - static-data:/app/staticfiles
      - media-data:/app/media
    ports:
      - 80:80
    depends_on:
      - app

volumes:
  static-data:
  media-data:
