# Generated by Django 5.0.8 on 2024-08-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
