name: Django CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.12.4]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
        pip install -r backend/requirements-dev.txt
    - name: Run Tests
      env:
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        DJANGO_DB_URL: ${{ secrets.DJANGO_DB_URL }}
        DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
        HOST: ${{ secrets.HOST }}
        DEBUG: ${{ secrets.DEBUG }}
      run: 
        python backend/coffee_shop/manage.py test
