# Generated by Django 5.0.8 on 2024-08-06 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Products",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100, verbose_name="name")),
                (
                    "description",
                    models.TextField(max_length=300, verbose_name="description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="price"
                    ),
                ),
                (
                    "available",
                    models.BooleanField(default=True, verbose_name="available"),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="logos", verbose_name="photo"
                    ),
                ),
            ],
        ),
    ]
