# Generated by Django 5.0.8 on 2024-08-08 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0002_rename_products_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="creation_date_time",
            field=models.DateTimeField(
                auto_now=True, verbose_name="creation_date_time"
            ),
        ),
    ]
