# Generated by Django 5.0.8 on 2024-08-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_product_creation_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="creation_date_time",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="creation_date_time"
            ),
        ),
    ]
