# Generated by Django 5.0.8 on 2024-08-17 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_product_creation_date_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="images/products", verbose_name="photo"
            ),
        ),
    ]
